server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update # or create-drop or none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    cloud:
      gateway:
        routes:
          - id: ops-user-service
            uri: lb://OPS-USER-SERVICE
            predicates:
              - Path=/api/v1/user-service/**
          - id: ops-member-service
            uri: lb://OPS-MEMBER-SERVICE
            predicates:
              - Path=/api/v1/member-service/**
          - id: discovery-service
            uri: lb://DISCOVERY-SERVICE
            predicates:
              - Path=/api/v1/discovery-service/**
          - id: ops-api-gateway
            uri: lb://OPS-API-GATEWAY
            predicates:
              - Path=/api/v1/api-gateway/**
          - id: ops-payment-service
            uri: lb://OPS-PAYMENT-SERVICE
            predicates:
              - Path=/api/v1/payment-service/**
          - id: ops-report-service
            uri: lb://OPS-REPORT-SERVICE
            predicates:
              - Path=/api/v1/report-service/**
          - id: integration-service
            uri: lb://INTEGRATION-SERVICE
            predicates:
              - Path=/api/v1/integration-service/**

#r2dbc:
#  url: r2dbc:postgresql://localhost:5432/postgres
#  username: postgres
#  password: 1234
#  driver: postgres

#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/your_database
#    username: postgres
#    password: 1234
#    driver: postgres


